version: '3.4'

services:

  message-queue:
    image: nats:linux
    networks:
      - ms-net

  megastore.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MESSAGE_QUEUE_URL=nats://message-queue:4222
      - APP_INSIGHTS_INSTRUMENTATION_KEY=31592f8a-0edd-4bc4-903f-a07ca0a2a37c
    ports:
      - 80
    depends_on:
      - message-queue
    networks:
      - ms-net

  megastore.savesalehandler:
    environment:
      - MESSAGE_QUEUE_URL=nats://message-queue:4222
      - APP_INSIGHTS_INSTRUMENTATION_KEY=31592f8a-0edd-4bc4-903f-a07ca0a2a37c
    env_file:
      - db-credentials.env
    depends_on:
      - message-queue
    networks:
      - ms-net

networks:
  ms-net: